// flow-typed signature: 7d0a0e420b96fca1f49fccc9f1b4adcf
// flow-typed version: <<STUB>>/normalize-scss_v^6.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize-scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize-scss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'normalize-scss/test/helper' {
  declare module.exports: any;
}

declare module 'normalize-scss/test/test_eyeglass' {
  declare module.exports: any;
}

declare module 'normalize-scss/test/test_fork-versions' {
  declare module.exports: any;
}

declare module 'normalize-scss/test/test_import-now' {
  declare module.exports: any;
}

declare module 'normalize-scss/test/test_normalize' {
  declare module.exports: any;
}

declare module 'normalize-scss/test/test_variables' {
  declare module.exports: any;
}

// Filename aliases
declare module 'normalize-scss/test/helper.js' {
  declare module.exports: $Exports<'normalize-scss/test/helper'>;
}
declare module 'normalize-scss/test/test_eyeglass.js' {
  declare module.exports: $Exports<'normalize-scss/test/test_eyeglass'>;
}
declare module 'normalize-scss/test/test_fork-versions.js' {
  declare module.exports: $Exports<'normalize-scss/test/test_fork-versions'>;
}
declare module 'normalize-scss/test/test_import-now.js' {
  declare module.exports: $Exports<'normalize-scss/test/test_import-now'>;
}
declare module 'normalize-scss/test/test_normalize.js' {
  declare module.exports: $Exports<'normalize-scss/test/test_normalize'>;
}
declare module 'normalize-scss/test/test_variables.js' {
  declare module.exports: $Exports<'normalize-scss/test/test_variables'>;
}
