// flow-typed signature: 76906a32283e29ee5d3c4a5ff96d3cfc
// flow-typed version: <<STUB>>/redux-responsive_v^4.1.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-responsive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-responsive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-responsive/index.min' {
  declare module.exports: any;
}

declare module 'redux-responsive/react' {
  declare module.exports: any;
}

declare module 'redux-responsive/react.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-responsive/index' {
  declare module.exports: $Exports<'redux-responsive'>;
}
declare module 'redux-responsive/index.js' {
  declare module.exports: $Exports<'redux-responsive'>;
}
declare module 'redux-responsive/index.min.js' {
  declare module.exports: $Exports<'redux-responsive/index.min'>;
}
declare module 'redux-responsive/react.js' {
  declare module.exports: $Exports<'redux-responsive/react'>;
}
declare module 'redux-responsive/react.min.js' {
  declare module.exports: $Exports<'redux-responsive/react.min'>;
}
