// flow-typed signature: 1a4a58d2ef0192de0b58462f2d45dc34
// flow-typed version: <<STUB>>/single-line-string_v0.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'single-line-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'single-line-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'single-line-string/dist' {
  declare module.exports: any;
}

declare module 'single-line-string/rollup.config' {
  declare module.exports: any;
}

declare module 'single-line-string/src/main' {
  declare module.exports: any;
}

declare module 'single-line-string/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'single-line-string/dist.js' {
  declare module.exports: $Exports<'single-line-string/dist'>;
}
declare module 'single-line-string/rollup.config.js' {
  declare module.exports: $Exports<'single-line-string/rollup.config'>;
}
declare module 'single-line-string/src/main.js' {
  declare module.exports: $Exports<'single-line-string/src/main'>;
}
declare module 'single-line-string/test/test.js' {
  declare module.exports: $Exports<'single-line-string/test/test'>;
}
