// flow-typed signature: e0e904e3f64e68b445fe971d3d04ba50
// flow-typed version: <<STUB>>/spin_v0.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'spin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spin/assets/fd-slider/fd-slider' {
  declare module.exports: any;
}

declare module 'spin/assets/prettify' {
  declare module.exports: any;
}

declare module 'spin/dist/spin' {
  declare module.exports: any;
}

declare module 'spin/dist/spin.min' {
  declare module.exports: any;
}

declare module 'spin/example/modernizr' {
  declare module.exports: any;
}

declare module 'spin/spin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spin/assets/fd-slider/fd-slider.js' {
  declare module.exports: $Exports<'spin/assets/fd-slider/fd-slider'>;
}
declare module 'spin/assets/prettify.js' {
  declare module.exports: $Exports<'spin/assets/prettify'>;
}
declare module 'spin/dist/spin.js' {
  declare module.exports: $Exports<'spin/dist/spin'>;
}
declare module 'spin/dist/spin.min.js' {
  declare module.exports: $Exports<'spin/dist/spin.min'>;
}
declare module 'spin/example/modernizr.js' {
  declare module.exports: $Exports<'spin/example/modernizr'>;
}
declare module 'spin/spin.js' {
  declare module.exports: $Exports<'spin/spin'>;
}
