/* @flow */
// Redux action type constants
export const START_DATE_CHANGE: string = 'START_DATE_CHANGE';
export const END_DATE_CHANGE: string = 'END_DATE_CHANGE';

export const FILTER_BY_AREA_TYPE: string = 'FILTER_BY_AREA_TYPE';
export const FILTER_BY_AREA_IDENTIFIER: string = 'FILTER_BY_AREA_IDENTIFIER';
export const FILTER_BY_AREA_CUSTOM: string = 'FILTER_BY_AREA_CUSTOM';

export const TOGGLE_CUSTOM_AREA_DRAW: string = 'TOGGLE_CUSTOM_AREA_DRAW';

export const FILTER_BY_TYPE_INJURY: string = 'FILTER_BY_TYPE_INJURY';
export const FILTER_BY_TYPE_FATALITY: string = 'FILTER_BY_TYPE_FATALITY';
export const FILTER_BY_NO_INJURY_FATALITY: string = 'FILTER_BY_NO_INJURY_FATALITY';

export const FILTER_BY_CONTRIBUTING_FACTOR: string = 'FILTER_BY_CONTRIBUTING_FACTOR';

export const CRASHES_ALL_REQUEST: string = 'CRASHES_ALL_REQUEST';
export const CRASHES_ALL_SUCCESS: string = 'CRASHES_ALL_SUCCESS';
export const CRASHES_ALL_ERROR: string = 'CRASHES_ALL_ERROR';

export const CONTRIBUTING_FACTORS_REQUEST: string = 'CONTRIBUTING_FACTORS_REQUEST';
export const CONTRIBUTING_FACTORS_SUCCESS: string = 'CONTRIBUTING_FACTORS_SUCCESS';
export const CONTRIBUTING_FACTORS_ERROR: string = 'CONTRIBUTING_FACTORS_ERROR';

export const CRASHES_YEAR_RANGE_REQUEST: string = 'CRASHES_YEAR_RANGE_REQUEST';
export const CRASHES_YEAR_RANGE_SUCCESS: string = 'CRASHES_YEAR_RANGE_SUCCESS';
export const CRASHES_YEAR_RANGE_ERROR: string = 'CRASHES_YEAR_RANGE_ERROR';

export const CRASHES_DATE_RANGE_REQUEST: string = 'CRASHES_DATE_RANGE_REQUEST';
export const CRASHES_DATE_RANGE_SUCCESS: string = 'CRASHES_DATE_RANGE_SUCCESS';
export const CRASHES_DATE_RANGE_ERROR: string = 'CRASHES_DATE_RANGE_ERROR';

export const CRASHES_MAX_DATE_REQUEST: string = 'CRASHES_MAX_DATE_REQUEST';
export const CRASHES_MAX_DATE_RESPONSE: string = 'CRASHES_MAX_DATE_RESPONSE';
export const CRASHES_MAX_DATE_ERROR: string = 'CRASHES_MAX_DATE_ERROR';

export const MODAL_OPENED: string = 'MODAL_OPENED';
export const MODAL_CLOSED: string = 'MODAL_CLOSED';
