export const START_DATE_CHANGE = 'START_DATE_CHANGE';
export const END_DATE_CHANGE = 'END_DATE_CHANGE';

export const FILTER_BY_AREA = 'FILTER_BY_AREA';
export const FILTER_BY_IDENTIFIER = 'FILTER_BY_IDENTIFIER';

export const FILTER_BY_TYPE_INJURY = 'FILTER_BY_TYPE_INJURY';
export const FILTER_BY_TYPE_FATALITY = 'FILTER_BY_TYPE_HARM';
export const FILTER_BY_NO_INJURY_FATALITY = 'FILTER_BY_NO_INJURY_FATALITY';

export const FILTER_BY_CONTRIBUTING_FACTOR = 'FILTER_BY_CONTRIBUTING_FACTOR';

export const CRASHES_ALL_REQUEST = 'CRASHES_ALL_REQUEST';
export const CRASHES_ALL_SUCCESS = 'CRASHES_ALL_SUCCESS';
export const CRASHES_ALL_ERROR = 'CRASHES_ALL_ERROR';

export const CONTRIBUTING_FACTORS_REQUEST = 'CONTRIBUTING_FACTORS_REQUEST';
export const CONTRIBUTING_FACTORS_SUCCESS = 'CONTRIBUTING_FACTORS_SUCCESS';
export const CONTRIBUTING_FACTORS_ERROR = 'CONTRIBUTING_FACTORS_ERROR';
