export const START_DATE_CHANGE = 'START_DATE_CHANGE';
export const END_DATE_CHANGE = 'END_DATE_CHANGE';

export const FILTER_BY_AREA_TYPE = 'FILTER_BY_AREA_TYPE';
export const FILTER_BY_AREA_IDENTIFIER = 'FILTER_BY_AREA_IDENTIFIER';
export const FILTER_BY_AREA_CUSTOM = 'FILTER_BY_AREA_CUSTOM';

export const FILTER_BY_LOCATION = 'FILTER_BY_LOCATION';

export const TOGGLE_CUSTOM_AREA_DRAW = 'TOGGLE_CUSTOM_AREA_DRAW';

export const FILTER_BY_TYPE_INJURY = 'FILTER_BY_TYPE_INJURY';
export const FILTER_BY_TYPE_FATALITY = 'FILTER_BY_TYPE_FATALITY';
export const FILTER_BY_NO_INJURY_FATALITY = 'FILTER_BY_NO_INJURY_FATALITY';

export const FILTER_BY_CONTRIBUTING_FACTOR = 'FILTER_BY_CONTRIBUTING_FACTOR';

export const CRASHES_ALL_REQUEST = 'CRASHES_ALL_REQUEST';
export const CRASHES_ALL_SUCCESS = 'CRASHES_ALL_SUCCESS';
export const CRASHES_ALL_ERROR = 'CRASHES_ALL_ERROR';

export const CONTRIBUTING_FACTORS_REQUEST = 'CONTRIBUTING_FACTORS_REQUEST';
export const CONTRIBUTING_FACTORS_SUCCESS = 'CONTRIBUTING_FACTORS_SUCCESS';
export const CONTRIBUTING_FACTORS_ERROR = 'CONTRIBUTING_FACTORS_ERROR';

export const CRASHES_YEAR_RANGE_REQUEST = 'CRASHES_YEAR_RANGE_REQUEST';
export const CRASHES_YEAR_RANGE_SUCCESS = 'CRASHES_YEAR_RANGE_SUCCESS';
export const CRASHES_YEAR_RANGE_ERROR = 'CRASHES_YEAR_RANGE_ERROR';

export const CRASHES_DATE_RANGE_REQUEST = 'CRASHES_DATE_RANGE_REQUEST';
export const CRASHES_DATE_RANGE_SUCCESS = 'CRASHES_DATE_RANGE_SUCCESS';
export const CRASHES_DATE_RANGE_ERROR = 'CRASHES_DATE_RANGE_ERROR';

export const CRASHES_MAX_DATE_REQUEST = 'CRASHES_MAX_DATE_REQUEST';
export const CRASHES_MAX_DATE_RESPONSE = 'CRASHES_MAX_DATE_RESPONSE';
export const CRASHES_MAX_DATE_ERROR = 'CRASHES_MAX_DATE_ERROR';

export const GEO_POLYGONS_REQUEST = 'GEO_POLYGONS_REQUEST';
export const GEO_POLYGONS_SUCCESS = 'GEO_POLYGONS_SUCCESS';
export const GEO_POLYGONS_ERROR = 'GEO_POLYGONS_ERROR';

export const MODAL_OPENED = 'MODAL_OPENED';
export const MODAL_CLOSED = 'MODAL_CLOSED';

// Geocoding a search location
export const LOCATION_GEOCODE_REQUEST = 'LOCATION_GEOCODE_REQUEST';
export const LOCATION_GEOCODE_SUCCESS = 'LOCATION_GEOCODE_SUCCESS';
export const LOCATION_GEOCODE_ERROR = 'LOCATION_GEOCODE_ERROR';
export const CLEAR_LOCATION_GEOCODE = 'CLEAR_LOCATION_GEOCODE';

export const LOCATION_SEARCH_REQUEST = 'LOCATION_SEARCH_REQUEST';
export const LOCATION_SEARCH_SUCCESS = 'LOCATION_SEARCH_SUCCESS';
export const LOCATION_SEARCH_ERROR = 'LOCATION_SEARCH_ERROR';

export const UPDATE_AUTOSUGGEST_VALUE = 'UPDATE_AUTOSUGGEST_VALUE';
export const CLEAR_SEARCH_SUGGESTIONS = 'CLEAR_SEARCH_SUGGESTIONS';
export const LOCATION_SEARCH_SELECT = 'LOCATION_SEARCH_SELECT';
